# =========================
# SwiftLint Configuration
# =========================

included:
  - Sources
excluded:
  - Tests
  - .build

# Rule configurations
line_length:
  warning: 100
  error: 120
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
    error: 4

identifier_name:
  min_length:
    warning: 3
    error: 2
  excluded:
    - id
    - URL
    - url
    - log
    - os
    - at
    - to
    - in

type_name:
  min_length:
    warning: 3
    error: 2
  excluded:
    - ID
    - URL

function_parameter_count:
  warning: 6
  error: 8

# Opt-in Rules
opt_in_rules:
  # Existing rules
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - explicit_self
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition
  
  # New rules
  - anonymous_argument_in_multiline_closure
  - computed_accessors_order
  - prefer_zero_over_explicit_init
  - redundant_self_in_closure
  - unavailable_function
  - unowned_variable_capture
  - void_function_in_ternary
  - capture_variable
  - closing_brace_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_optional_boolean
  - empty_enum_arguments
  - explicit_type_interface
  - extension_access_modifier
  - fallthrough
  - file_header
  - file_name
  - file_types_order
  - first_where
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_objc_type
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_parameters_brackets
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_deinit
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - test_case_accessibility
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition

# Analyzer rules
analyzer_rules:
  - capture_variable
  - explicit_self
  - unused_declaration
  - unused_import

# Custom rules for British English
custom_rules:
  british_spelling:
    name: "British Spelling"
    regex: '(?i)(color|behavior|flavor|humor|labor|neighbour|rumor|splendor|harbor)'
    message: "Use British English spelling (colour, behaviour, flavour, humour, labour, neighbour, rumour, splendour, harbour)"
    severity: warning
    match_kinds:
      - comment
      - string
  
  british_spelling_ise:
    name: "British -ise Spelling"
    regex: '(?i)(organize|authorize|customize|initialize|synchronize|standardize|minimize|maximize)'
    message: "Use British English -ise spelling (organise, authorise, customise, initialise, synchronise, standardise, minimise, maximise)"
    severity: warning
    match_kinds:
      - comment
      - string

disabled_rules:
  - todo
  - trailing_whitespace  # Handled by SwiftFormat
  - vertical_whitespace  # Handled by SwiftFormat

# Deployment target
deployment_target:
  macOS_deployment_target: "14.0"
